add a function of downloading monthly efforts by project csv
kiconiaworks/kippo pull request #1
Opened 2023-08-15 09:47 UTC by takedaami

https://github.com/orgs/kiconiaworks/projects/1#card-89992779

2023-08-15 10:16 UTC, monkut commented on kippo/projects/admin.py
> +                default_start=datetime(2023, 8, 1),
こちらは、動的に今月の日付になるように更新しましょう。

2023-08-15 10:16 UTC, monkut commented on kippo/projects/admin.py
> +    actions = "download_csv"
ここは更新する必要があったでしょうか？

2023-08-15 10:16 UTC, monkut commented on kippo/kippo/settings/base.py
> +Django _settings for kippo project.
こちらの`_settings`の変更はどいう役割します？

2023-08-15 10:16 UTC, monkut commented on kippo/kippo/settings/base.py
> +    "daterange.apps.DateRangeFilterConfig",
rangefilterからDateTimeRangeFilterBuilderをインポートして、使われているようですが、これは必要でしょうか？

2023-08-15 10:16 UTC, monkut commented on kippo/projects/functions.py
> +def generate_projectweeklyeffort_csv(user_id: str, key: str, queryid, from_datetime_isoformat: Optional[str] = None) -> None:
このqueryidとは、ProjectWeeklyEffortのIDに見えるが、projectsとfrom_datetime_isoformatで必要な情報が取れそうです。

Filterで設定している期間を渡したほうが良さそうです。

2023-08-15 10:16 UTC, monkut commented on kippo/projects/functions.py
> +            "project": KippoProject.objects.get(id=project).name,
すでにunique_projectsを準備しているので、キャッシュのものを使いましょう。
これだと、毎回Queryが発生します。

2023-08-15 10:16 UTC, monkut commented on kippo/projects/functions.py
> +        row.update(user_hours)
ここでrowのdictを作っているので、 updateが不用かと思います。
この状態だと、集計されないように見えます。

2023-08-18 04:11 UTC, maruko081 commented on kippo/kippo/settings/base.py
> +    "daterange.apps.DateRangeFilterConfig",
"rangefilter"こちらは必要ですが、
"daterange.apps.DateRangeFilterConfig"は要らなかったです！

2023-08-18 04:11 UTC, maruko081 commented on kippo/projects/admin.py
> +    actions = "download_csv"
ありませんでした。

2023-08-18 04:11 UTC, maruko081 commented on kippo/projects/functions.py
> +def generate_projectweeklyeffort_csv(user_id: str, key: str, queryid, from_datetime_isoformat: Optional[str] = None) -> None:
このqueryidはテーブルデータのうち、チェックをつけたデータを表すidです。それを用いて選択されたデータだけをaction(download csv)に反映する機能をつけるためのものですが、projectsとfrom_datetime_isoformatで必要な情報が取れますか？
（既存のactionであるdownloadcsvは選択した範囲に関わらず全てのデータがダウンロードされてしまうので、そこを改善しました。）

2023-08-18 04:11 UTC, takedaami commented on kippo/kippo/settings/base.py
> +Django _settings for kippo project.
ローカルで開いた時にうまく動かず少し変えたままにしてしまいました。
元に戻します！

2023-08-18 04:11 UTC, takedaami commented on kippo/projects/admin.py
> +                default_start=datetime(2023, 8, 1),
更新しました！

2023-08-18 04:11 UTC, takedaami commented on kippo/projects/functions.py
> +            "project": KippoProject.objects.get(id=project).name,
修正します！

2023-08-18 04:11 UTC, takedaami commented on kippo/projects/functions.py
> +        row.update(user_hours)
修正します！

2023-08-18 06:54 UTC, monkut requested changes
”rangefilter"を追加しているようなので、Pipfileの更新のコミットが必要なので、追加をお願いします。

2023-08-18 06:54 UTC, monkut commented on kippo/projects/admin.py
> +    actions = "download_csv"
更新が不要なら、戻っしてください。

2023-08-18 06:54 UTC, monkut commented on kippo/projects/functions.py
> +def generate_projectweeklyeffort_csv(user_id: str, key: str, queryid, from_datetime_isoformat: Optional[str] = None) -> None:
たしかにActionを実行するには、チェックが必要ですが、チェックに入ったデータが不要で、Filterで選択したデータのみでよさそうです。ProjectWeeklyEffortを一つつづを選んでそのデータだけを出すことはないと考えています。

queryidを置くなら、より明確な変数名とタイプをつけるとよいですね。この場合なら、effort_idsが良さそうです。

2023-08-18 07:18 UTC, takedaami commented on kippo/projects/functions.py
> +def generate_projectweeklyeffort_csv(user_id: str, key: str, queryid, from_datetime_isoformat: Optional[str] = None) -> None:
チェックを入れないとactionが実行されないならば、generate_projectweeklyeffort_csv、generate_projectmonthlyeffort_csvどちらもチェックを入れたデータだけが出力されるという方が直感的なUIで扱いやすい気がするので(全選択のチェックもできるので)、queryidは置きたいと思います。関数名は修正します！

2023-08-18 08:46 UTC, monkut commented on kippo/projects/functions.py
> +        ProjectWeeklyEffort.objects.filter(project__in=projects, id__in=queryid).values("project", "user").annotate(hours=Sum("hours"))
これだと、filter選択している期間が反映されない状況です。
（queryidで渡せているなら対応ですが、この関数には、期間の開始・終了を渡したほうがわかりやすい

週単位の日付対応はannotateでできないので、ProjectWeeklyEffortの日付ごとに対応すると良さそうです。

2023-08-18 08:48 UTC, monkut commented on kippo/projects/functions.py
> +    unique_projects = set(e["project"] for e in effort_monthly_entries)
`effort_monthly_entries` を処理ならがら、とれるので、ここでの取り出しが不要のように見えます。

`row`のデータはこのようになるとよい：

```
row[project_name][(month, username)]

```

2023-10-11 04:17 UTC, monkut requested changes

2023-10-11 04:17 UTC, monkut commented on kippo/_settings/base.py
> +# kippo/_settings/local.py:
こちらが追加されたようですが、不要のように見えます。
不要なら削除をお願いします。

2023-10-11 04:17 UTC, monkut commented on kippo/kippo/.ipynb_checkpoints/urls-checkpoint.py
> +"""kippo URL Configuration
こちらは不要なはずです。
削除をお願いします

2023-10-11 04:17 UTC, monkut commented on kippo/kippo/.ipynb_checkpoints/wsgi-checkpoint.py
> +"""
こちらは不要なはずです。
削除をお願いします

2023-10-11 04:17 UTC, monkut commented on kippo/kippo/settings/.ipynb_checkpoints/production-checkpoint.py
> +from .base import *
こちらは不要なはずです。
削除をお願いします

2023-10-11 04:17 UTC, monkut commented on kippo/projects/.ipynb_checkpoints/urls-checkpoint.py
> +from django.conf.urls import url
こちらは不要なはずです。
削除をお願いします

2023-10-11 04:17 UTC, monkut commented on kippo/projects/.ipynb_checkpoints/views-checkpoint.py
> +import logging
こちらは不要なはずです。
削除をお願いします

2023-10-11 04:17 UTC, monkut commented on kippo/projects/admin.py
> +    from datetime import datetime, timedelta
こちらのimportはファイルの上位部においてください。

2023-10-11 04:17 UTC, monkut commented on kippo/projects/admin.py
> +        today = datetime.today()
today()が設定されているタイムゾーンの今日のことになります。
このシステムの運用は、UTCで運用しているため、日本との時差が発生してしまいます。

こちらを`today = timezone.localdate()`に更新してください。(こちらは、settings.pyで設定しているTIMEZONEによって、更新されます。


`from django.utils import timezone`をインポート

2023-10-11 04:17 UTC, monkut commented on kippo/projects/admin.py
> +            now = timezone.now()
こちらもJSTに変換しましょう。

`now = now.astimezone(settings.JST)`

2023-10-11 04:17 UTC, monkut commented on kippo/projects/admin.py
> +    download_monthly_csv.description = _("Download ProjectMonthlyEffort CSV")
djangoの新しいdecoratorを追加いましょう

こちらの代わりにmethodの上にこちらを定義：
```
@admin.display(description=_("Download ProjectMonthlyEffort CSV"))
```

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +        effort_entries = ProjectWeeklyEffort.objects.filter(project__in=projects, id__in=effort_id).order_by("project", "week_start", "user")
こちらがもともとあるものでしょうかね？
こちらの改修の必要性を教えてくれますか？

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +    monthly_effort = defaultdict(int)
`defaultdict(int)`の代わりに`from collections import Counter` の`Counter()`で良さそうです。

2023-10-11 04:17 UTC, monkut commented on kippo/projects/admin.py
> +    def get_current_month_start_end():
別のところで`calendar.monthrange`を使っているので、そこを使えばこちらは不要ですかね？
```
last_day_of_month = calendar.monthrange(effort.week_start.year, effort.week_start.month)[1]
```

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +            monthly_effort[(effort.project.name, effort.user.display_name, month_key_current)] += (effort.hours * days_in_current_month) / 7
monthly_effort_keyを切り出して定義しましょう。

```
monthly_effort_key = (effort.project.name, effort.user.display_name, month_key_current)
```

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +def generate_projectmonthlyeffort_csv(user_id: str, key: str, effort_id: List[int], from_datetime_isoformat: Optional[str] = None) -> None:
`effort_id`が複数系のようなので、`effort_ids`に更新してください。

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +        days_in_current_month = last_day_of_month - effort.week_start.day + 1
こちらの用途についてコメントの追加をお願いします。

変数名を更新しましょう。`days_in_current_month`を読むと`last_day_of_month`と一緒になる気がします。

ここでは、残りの日数として使っているようです。
ならば、`current_month_remaining_days`が適切ですかね？

2023-10-11 04:17 UTC, monkut commented on kippo/projects/functions.py
> +        else:
２０１行目で`+1`をしているので、この分岐には入らないようです。

2023-10-11 04:17 UTC, monkut commented on kippo/projects/management/commands/dumpdata_to_s3.py
> +            raise CommandError("_settings.DUMPDATA_S3_BUCKETNAME not configured!")
`_settings` が不要なはずです。戻ししてください。

2023-10-11 04:17 UTC, monkut commented on kippo/tasks/.ipynb_checkpoints/views-checkpoint.py
> +import logging
不要です。削除してください。

2023-10-11 04:17 UTC, monkut commented on kippo/projects/tests/test_functions.py
> +        # create ProjectMonthlyEffort
こちらは、最初の週と最後の週の２ヶ月分のデータをいれて、試験を回してください。

2023-10-11 05:51 UTC, monkut requested changes
- 不要な.ipynbファイルの削除をお願いします
- マージ問題の解決もお願いします。
- テストケースの更新をお願いします。

2023-10-11 05:51 UTC, monkut commented on kippo/projects/tests/test_functions.py
> +        queryset_count = str(ProjectWeeklyEffort.objects.all().count())
このあと、str() -> int()変換しているので、ここでstr()への変換が不要のようです。

2023-10-12 00:42 UTC, monkut reviewed
確認です。
最初の週を入れています？

2023-10-12 00:42 UTC, monkut commented on kippo/projects/tests/test_functions.py
> +        # create ProjectMonthlyEffort
最初の週を入れています？

2023-10-16 01:19 UTC, monkut requested changes
まだ、`_settings`が残っているようです。削除をお願いします。

あと、いくつかのレビューコメントを対応していないようなので、対応が不要だと考えているなら、そのコメントに対して、返事をお願いします。

2023-10-16 01:19 UTC, monkut commented on kippo/_settings/base.py
> +# kippo/_settings/local.py:
削除をお願いします。

2023-10-18 03:37 UTC, takedaami commented on kippo/projects/tests/test_functions.py
> +        # create ProjectMonthlyEffort
最初の週と最後の週を2ヶ月分（2023/07, 2023/08）入れました！

2023-10-18 03:38 UTC, takedaami commented on kippo/projects/tests/test_functions.py
> +        queryset_count = str(ProjectWeeklyEffort.objects.all().count())
修正しました！

2023-10-19 02:35 UTC, takedaami commented
> 確認です。 最初の週を入れています？

2023-10-20 04:20 UTC, monkut approved these changes

2023-10-20 04:21 UTC, merged